server.port=3002
server.address=0.0.0.0
spring.application.name=whatsapp-webhook



# BGS API Configuration
bgs.base-url=${NEXT_PUBLIC_API_BASE_URL:https://be.bgsinfotech.com}
bgs.tenant-id=${NEXT_PUBLIC_TENANT_ID:697c756692a4f15176fefe8e}

# AiSensy Configuration
aisensy.api-key=${AISENSY_API_KEY:577d0643178707e58a3b0}
aisensy.project-id=${AISENSY_PROJECT_ID:69da0b7a7dec1710f8a9db08}

